# Generated by Django 3.1.7 on 2021-04-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210331_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.URLField(),
        ),
    ]
